### PR TITLE
blog URL changed

### PR DESCRIPTION
**Pull request by hasancse91**
I've changed the URL of my blog site

### CODE REVIEW

**Comment by hatanvir** [comment]
Ok brother got it :) .

**Comment by hasancse91** [comment]
Nope! You used the URL of my SharedPreferences blog post. I changed it to `Development Guideline` blog post URL

**Review by hatanvir — APPROVED** [review]
Thanks, bro.And write more topic about android :)

**Comment by hasancse91** [comment]
Sure!

**Comment by hatanvir** [comment]
Yes brother.Thanks :)

**Pull request closed without merging**
